export const SET_GAME_ID = 'SET_GAME_ID'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_USERS_POSITIONS = 'SET_USERS_POSITIONS'
export const SET_INDEX = 'SET_INDEX'
export const SET_MESSAGE_ID = 'SET_MESSAGE_ID'
export const SET_USERS_PROPERTIES = 'SET_USERS_PROPERTIES'
export const SET_CASH = 'SET_CASH'
export const SET_USERS_MONEY = 'SET_USERS_MONEY'
export const SET_MYINDEX = 'SET_MYINDEX'
export const SET_STATE = 'SET_STATE'

